apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openfaas-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Abdullah-0-3/serverless-gitops-integration
  ref:
    branch: main
  timeout: 60s
