apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openfaas-gitops
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/cluster/openfaas-functions
  prune: true
  sourceRef:
    kind: GitRepository
    name: openfaas-source
  targetNamespace: openfaas-fn
  timeout: 1m
  validation: client
