apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: hello-fn
  namespace: openfaas-fn
spec:
  image: muhammadabdullahabrar/openfaas-function:latest
  labels:
    app: hello-fn
  annotations:
    topic: http
  environment:
    write_debug: true
